name: dsh-zip-builder

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            suffix: windows-x64
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: pwd

