name: dsh-zip-builder

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            suffix: windows-x64
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 24
      - run: |
          New-Item -Path ".\bin" -ItemType Directory
          Set-Location ".\bin"
          npm i @deepseek-ai/dsh@latest pnpm@latest
          Copy-Item ((node -p "process.execPath").Trim()) ".\node.exe" -Force
          Remove-Item -Path .\package.json -Force
          tree /F

